export { Header } from "./Header";
export { Hero } from "./Hero";
export { EditalInfo } from "./EditalInfo";
export { Eixos } from "./Eixos";
export { Timeline } from "./Timeline";
export { Origin } from "./Origin";
export { About } from "./About";
export { FAQ } from "./FAQ";
export { Footer } from "./Footer";
