/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiPublicHooksStatusChangedRouteImport } from './routes/api/public/hooks/status-changed'
import { Route as ApiPublicHooksLembretesEditalRouteImport } from './routes/api/public/hooks/lembretes-edital'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksStatusChangedRoute =
  ApiPublicHooksStatusChangedRouteImport.update({
    id: '/api/public/hooks/status-changed',
    path: '/api/public/hooks/status-changed',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLembretesEditalRoute =
  ApiPublicHooksLembretesEditalRouteImport.update({
    id: '/api/public/hooks/lembretes-edital',
    path: '/api/public/hooks/lembretes-edital',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/status': typeof StatusRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/public/hooks/lembretes-edital': typeof ApiPublicHooksLembretesEditalRoute
  '/api/public/hooks/status-changed': typeof ApiPublicHooksStatusChangedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/status': typeof StatusRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/public/hooks/lembretes-edital': typeof ApiPublicHooksLembretesEditalRoute
  '/api/public/hooks/status-changed': typeof ApiPublicHooksStatusChangedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/status': typeof StatusRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/public/hooks/lembretes-edital': typeof ApiPublicHooksLembretesEditalRoute
  '/api/public/hooks/status-changed': typeof ApiPublicHooksStatusChangedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/status'
    | '/admin/login'
    | '/api/public/hooks/lembretes-edital'
    | '/api/public/hooks/status-changed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/status'
    | '/admin/login'
    | '/api/public/hooks/lembretes-edital'
    | '/api/public/hooks/status-changed'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastro'
    | '/status'
    | '/admin/login'
    | '/api/public/hooks/lembretes-edital'
    | '/api/public/hooks/status-changed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  StatusRoute: typeof StatusRoute
  ApiPublicHooksLembretesEditalRoute: typeof ApiPublicHooksLembretesEditalRoute
  ApiPublicHooksStatusChangedRoute: typeof ApiPublicHooksStatusChangedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/status-changed': {
      id: '/api/public/hooks/status-changed'
      path: '/api/public/hooks/status-changed'
      fullPath: '/api/public/hooks/status-changed'
      preLoaderRoute: typeof ApiPublicHooksStatusChangedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/lembretes-edital': {
      id: '/api/public/hooks/lembretes-edital'
      path: '/api/public/hooks/lembretes-edital'
      fullPath: '/api/public/hooks/lembretes-edital'
      preLoaderRoute: typeof ApiPublicHooksLembretesEditalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CadastroRoute: CadastroRoute,
  StatusRoute: StatusRoute,
  ApiPublicHooksLembretesEditalRoute: ApiPublicHooksLembretesEditalRoute,
  ApiPublicHooksStatusChangedRoute: ApiPublicHooksStatusChangedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
